[package]
name = "senso"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
itertools = "0.10.5"
lazy_static = "1.4.0"
lm-sensors = "0.1.5"
log = "0.4.17"
ratatui = "0.20.1"
